version: "3"
services:
  bot:
    image: bot_image
    build:
      context: ./bot
    volumes:
      - pg_logs:/tmp/
    environment:
      - TOKEN=${TOKEN}
      - RM_HOST=${RM_HOST}
      - RM_USER=${RM_USER}
      - RM_PORT=${RM_PORT}
      - RM_PASSWORD=${RM_PASSWORD}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
    container_name: 'bot'
  db:
    image: db_image
    build: ./db
    volumes:
      - pg_logs:/tmp/
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - DB_REPL_USER=${DB_REPL_USER}
      - DB_REPL_PASSWORD=${DB_REPL_PASSWORD}
      - DB_REPL_HOST=${DB_REPL_HOST}
      - DB_PORT=${DB_PORT}
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
      - POSTGRES_HOST_AUTH_METHOD="host replication ${DB_REPL_USER} ${DB_REPL_HOST}/24 trust\n host all all 192.168.199.1/32 password"
#      - POSTGRES_INITDB_ARGS="--auth-host=scram-sha-256"
    container_name: "db"
    command: |
      postgres
      -c wal_level=replica
      -c hot_standby=on
      -c max_wal_senders=10
      -c max_replication_slots=10
      -c hot_standby_feedback=on
      -c wal_log_hints=on
      -c log_replication_commands=on
      -c listen_addresses='*'
      -c port=${DB_PORT}
      -c logging_collector=on
      -c log_directory='/tmp/postgresql/'
      -c log_filename='postgresql.log'
  db_repl:
    image: db_repl_image
    build: ./db_repl
    container_name: "db_repl"
    environment:
      - PGUSER=${DB_REPL_USER}
      - PGPASSWORD=${DB_REPL_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_REPL_USER=${DB_REPL_USER}
      - DB_REPL_PASSWORD=${DB_REPL_PASSWORD}
      - DB_REPL_HOST=${DB_REPL_HOST}
      - DB_REPL_PORT=${DB_REPL_PORT}
    volumes:
      - ./customPostgresql.conf:/etc/postgresql.conf
    command: |
      bash -c "
      rm -rf /var/lib/postgresql/data/*
      until pg_basebackup --pgdata=/var/lib/postgresql/data -R -U ${DB_REPL_USER} --host=${DB_HOST} --port=${DB_PORT} -P -w
      do
      echo 'Waiting for primary to connect...'
      sleep 1s
      done
      echo 'Backup done, starting replica...'
      su postgres
      chmod 0700 /var/lib/postgresql/data
      su - postgres
      psql -f /usr/lib/postgresql/15/bin
      "
     # postgres -c listen_addresses='*'
     # postgres -c config_file=/etc/postgresql.conf
    depends_on:
      - db
volumes:
  pg_logs:

