CREATE USER ${DB_REPL_USER} WITH REPLICATION PASSWORD '${DB_REPL_PASSWORD}';
CREATE DATABASE ${DB_DATABASE};
\c ${DB_DATABASE};

CREATE TABLE IF NOT EXISTS Phones (
    id SERIAL PRIMARY KEY,
    PhoneName VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS Emails (
    id SERIAL PRIMARY KEY,
    EmailName VARCHAR(255) NOT NULL
);

INSERT INTO Emails (EmailName) VALUES
('test@test.ru'),
('ivanov_a@pt.ru');

INSERT INTO Phones (PhoneName) VALUES
('86666666666'),
('+7 495 744 01 44');
